### ISSUE TITLE
Simulations: tiny technical detail question for @martinhronec

### ISSUE THREAD

**Issue by KarolinaChalupova** [KarolinaChalupova/DiplomaThesis#13]
@martinhronec 
I'm in the process of simulating the returns. In [Gu et al., Internet Appendix A](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/rfs/33/5/10.1093_rfs_hhaa009/4/hhaa009_supplementary_data.pdf?Expires=1608289302&Signature=j14sSphYY2NrdgKib~nKyWXhnE~LTHIL3--MbhQAJ3OrU1Bbragkbiyl3iaIW-aeOXIHElDdoo6twWkdEwb8-7LrqWmVevtaEYU83S1a9CHVAt6poVgKpPzc27Mi5ysNHHe1hEMU3pJrBOHzc3nO3foySqkKQqECa7OADtsx0UJBv2~wMSP8p-1hIegxIODk~6wEUl7oGipacS-Yk4UEFIpN3gaJxiqYbS0oSLdSbE8R8Le-lbAnJH80IGFfxDzRYc9GZgqseVcd36N7eaoNO~P4tM3NzUSyzqbRa6cJOtue8FYG2C5p9EAQAN0UrIMJKxFUsc4Rt-D2DZEqYI1r~g__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA), around line 6 page 1 I read: 

"in which their variances are calibrated so that the average time series R^2 is 40%". 

What do they mean by average timeseries R^2? Does it mean: run auto-regression of return in t+1 on return in t for all firms, calculate R^2, and take average across firms? Thanks!

**Comment by martinhronec** [comment]
@KarolinaChalupova not sure, but I believe they are not talking about returns but the error-generating equation. R^2 (IS and predictive) also depend on function g, and they calibrate it to be 50% cross-sectional and 5% predictive, as they mention later in the online appendix.

**Comment by KarolinaChalupova** [comment]
@martinhronec  Yes, you must be right, that makes perfect sense. I think I now know how to re-calibrate if necesary.

Folloup question: when simulating the features z_it, they use the interaction with "macroeconomic variable" x_t. Do you think I should include it? (Advantage: I would run the exact same simulation as Kelly (including calibration). Disadvantage: I do not have macroeconomic interactions in data, so it correponds to my prediction task less closely). Alternatively, I can simply omit it in the simulation (and recalibrate). What do you think?

**Comment by martinhronec** [comment]
@KarolinaChalupova doen't really matter to be honest, problem can be rewritten both ways (from characteristics to factors), but for clarity of exposition I would keep it similar to the data you have.

**Comment by KarolinaChalupova** [comment]
@martinhronec Perfect, thank you! Managed to write the simulations and training on them now. Thanks!
