### ISSUE TITLE
Liquidity filter - do I have the right data from @martinhronec? 

### ISSUE THREAD

**Issue by KarolinaChalupova** [KarolinaChalupova/DiplomaThesis#3]
@martinhronec  Tomas mentioned that there was a problem with the liquidity filter. I do not have the code of your liquidity filter, just the dscodes that pass the filter. Tomas said that the filter was more strict than it should be. I just want to make sure I have the right data. Even if I dont, this may be immaterial, as the filter is not wrong, just strict.

**Comment by martinhronec** [comment]
@KarolinaChalupova, send me the name of the datafiles you have, please.

**Comment by KarolinaChalupova** [comment]
@martinhronec filenames: DST_returns.gzip, DST_signals.gzip, DST_universe_filter.gzip

**Comment by martinhronec** [comment]
Open it and check if there are US companies or not.

**Comment by KarolinaChalupova** [comment]
@martinhronec There are no US companies, just Europe, Asia and Japan. In DST_signals, there are 30,088 unique DTID. After applying the DST_universe_filter, this reduces to 8,350 unique DTID.

**Comment by KarolinaChalupova** [comment]
@martinhronec  Also, could you please send me the code for the filter and data cleaning (to see how the DST_universe_filter is obtained)?

**Comment by martinhronec** [comment]
@KarolinaChalupova data cleaning and filtering code shared as well as WRDS_data files. 
There is a lot of going on in data-preprocessing, I would not dedicate too much time to it right now.
