### ISSUE TITLE
Use smaller number of features

### ISSUE THREAD

**Issue by KarolinaChalupova** [KarolinaChalupova/DiplomaThesis#6]
Možná by dávalo smysl použít i menší množství features, protože napříč Kellym (Gu et al, 2018) a vlastně i napříč ostatní literaturou mi připadá, že se modely hodně shodují ve výběru důležitých proměnných, takže bych je prozatím mohla vzít jako dané. Řekla bych, že když bude menší množství features, bude ta interpretabilita daleko přehlednější, což je podle mě dobrý, protože se v tom já i čtenář líp zorientujeme. Viděla bych okolo 30 features namísto současných 150.

@martinhronec  what do you think?

**Comment by martinhronec** [comment]
30 je ok pre zatial, skus teda vybrat na zaklade Kellyho pripadne [OTMH](https://www.sciencedirect.com/science/article/pii/S1386418120300574).

**Comment by barunik** [comment]
souhlasim, urcite dava smysl vybrat 30 features na zaklade Kellyho

**Comment by KarolinaChalupova** [comment]
1. Is this only for now, or for the entire thesis? 
2. Given that Kelly uses US data and characterisits importance differs across regions (OTMH) and I will be choosing characteristics based on Kelly, It would make sense to use US data for me as well (#2)

**Comment by KarolinaChalupova** [comment]
Features in top 30 in Kelly that I think are not present in OTMH (and therefore not present in my data): 
- mom12m 
- chmom 
- dolvol
- nincr - is quarterly 
- mom36m 
- securedind 
- convind 
- depr
- betasq
- cashpr

**Comment by KarolinaChalupova** [comment]
We agreed with @martinhronec to choose 30 top from OTMH, as there are problems with Kelly: 
- Kelly ignores transaction costs and illiquidity, so their top anomalies are due to illiquidity, while my dataset is liquid just as OTMH is, so I choose based on OTMH. 
- also, my region corresponds to OTMH (global) more than to Kelly (US) and anomalies are somewhat region specific
- I dont have 10 out of 30 most important Kelly variables in the dataset.
